print("Hello World!")
name=input("What is your name?")
print("Nice to meet you " ,name, ".")
fav_Color=input("What is your favorite color?")
maj=input("What is your major?")
print("Well, nice to meet you " ,name, ". I love the color " ,fav_Color, ", and " ,maj, " is a cool major.")